### ISSUE TITLE
support option to default value when add environment variable into manifest.json file 

### ISSUE THREAD

**Issue by quaiji** [TIBCOSoftware/tibcli-node#1]
When use "tibcli-node manifest add-var" to add variable into manifest, no way to specify default value for added variable. Should have an option to default value.

Consider the below scenario. 
1. The "onPremise_ip" is exposed as the nodejs app property. Here the default ip address is "10.97.106.47"
let host_ip = process.env.onPremise_ip||"10.97.106.47";
2. After push the nodejs app, though default value is specified in nodejs app, but it won't be displayed on UI.
3. Then customer update the property to use another ip address.
4. After step 3, for some reason, customer want to switch the ip address back to default one, as long as no property value specified, the default ip address will be used. But here comes the issue, the property value field can't be set empty. 
5. Then Customer has to check the nodejs code to get the default value and put it on UI which is not good.

If tibcli-nodejs can specify default value, customer can switch ip back and forth to default one.

**Comment by retgits** [comment]
Hi! Great feedback! We've just released version 0.4.1 which has this feature.
To specify a default value you can use:
```
$ tibcli-node manifest add-var -N DB_USER -T string -v admin
```
To upgrade to the latest release of this package use
```
$ npm upgrade -g tibcli-node
```
